# Generated by Django 5.0.6 on 2024-06-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.JSONField(default=[]),
        ),
    ]
