# Generated by Django 5.0.6 on 2024-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tags_alter_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
