# Generated by Django 5.0.6 on 2024-06-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_tag_remove_movie_tags_movie_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('seat_rows', models.IntegerField(default=10)),
                ('seat_cols', models.IntegerField(default=20)),
            ],
        ),
    ]
