# Generated by Django 5.0.6 on 2024-06-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_moviescreening_seats_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
