# Generated by Django 5.0.6 on 2024-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(default=1, upload_to='movies/covers'),
            preserve_default=False,
        ),
    ]
