# Generated by Django 5.0.6 on 2024-07-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(default='media/movies/covers/default.webp', upload_to='media/movies/covers'),
        ),
    ]
