# Generated by Django 5.0.6 on 2024-07-11 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaroom',
            name='seat_cols',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cinemaroom',
            name='seat_rows',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)]),
        ),
    ]
