# Generated by Django 5.0.6 on 2024-07-13 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_cinemaroom_seat_cols_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('screening', 'user')},
        ),
    ]
